name:                tikzsd
version:             1.0.0

github:              "anthonyywangmath/tikzsd"
license:             MIT
author:              "Anthony Wang"
maintainer:          "anthony.y.wang.math@gmail.com"
copyright:           "2021 Anthony Wang"
category:            Math

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            A program for generating LaTeX code of string diagrams.
description:         Please see the README on GitHub at <https://github.com/anthonyywangmath/tikzsd#readme>

dependencies:
- base >= 4.7 && < 5
- transformers >= 0.5.6 && < 0.6
- parsec >= 3.1.14 && < 3.2
- array >= 0.5.4 && < 0.6
- containers >= 0.6.2 && < 0.7
- mtl >= 2.2.2 && < 2.3
- lens >= 4.19 && < 5.1

library:
  source-dirs: src

executables:
  tikzsd:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tikzsd

tests:
  tikzsd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tikzsd
